apiVersion: apps/v1
kind: Deployment
metadata:
   name: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
       app: springboot
  template: 
    metadata:
      name: calculator-app
      labels:
        app: springboot
    spec:
      containers:
      - name: calculator-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080

